FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY transformer.py .
COPY proto/ proto/
RUN apt-get update && apt-get install -y ffmpeg
CMD ["python", "transformer.py"]