prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  adminPassword: prom-operator
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    size: 5Gi

alertmanager:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
