apiVersion: apps/v1
kind: Deployment
metadata:
  name: bias-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bias-worker
  template:
    metadata:
      labels:
        app: bias-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: bias-worker
        image: gcr.io/datacenter-437321/bias-worker:latest
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
