apiVersion: apps/v1
kind: Deployment
metadata:
  name: bias-worker
  labels:
    app: bias-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bias-worker
  template:
    metadata:
      labels:
        app: bias-worker
    spec:
      containers:
      - name: bias-worker
        image: gcr.io/datacenter-437321/bias-worker:latest
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: BIAS_SERVICE_HOST
          value: "bias-worker:50051"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: bias-worker
spec:
  selector:
    app: bias-worker
  clusterIP: 192.168.241.72
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP