# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import bias_detection_pb2 as proto_dot_bias__detection__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/bias_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BiasDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeBias = channel.unary_unary(
                '/bias_detection.BiasDetection/AnalyzeBias',
                request_serializer=proto_dot_bias__detection__pb2.BiasRequest.SerializeToString,
                response_deserializer=proto_dot_bias__detection__pb2.BiasResponse.FromString,
                _registered_method=True)


class BiasDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeBias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiasDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeBias': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBias,
                    request_deserializer=proto_dot_bias__detection__pb2.BiasRequest.FromString,
                    response_serializer=proto_dot_bias__detection__pb2.BiasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bias_detection.BiasDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bias_detection.BiasDetection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BiasDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeBias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bias_detection.BiasDetection/AnalyzeBias',
            proto_dot_bias__detection__pb2.BiasRequest.SerializeToString,
            proto_dot_bias__detection__pb2.BiasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
