# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/bias_detection.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/bias_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/bias_detection.proto\x12\x0e\x62ias_detection\"#\n\x0b\x42iasRequest\x12\x14\n\x0ctext_content\x18\x01 \x01(\t\":\n\x0c\x42iasResponse\x12\x12\n\nbias_score\x18\x01 \x01(\x02\x12\x16\n\x0e\x62iased_phrases\x18\x02 \x03(\t2[\n\rBiasDetection\x12J\n\x0b\x41nalyzeBias\x12\x1b.bias_detection.BiasRequest\x1a\x1c.bias_detection.BiasResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bias_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIASREQUEST']._serialized_start=46
  _globals['_BIASREQUEST']._serialized_end=81
  _globals['_BIASRESPONSE']._serialized_start=83
  _globals['_BIASRESPONSE']._serialized_end=141
  _globals['_BIASDETECTION']._serialized_start=143
  _globals['_BIASDETECTION']._serialized_end=234
# @@protoc_insertion_point(module_scope)
